config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('single_pages.urls')),
    path('post/', include('post.urls')),
    path('admin/', admin.site.urls),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from . import views

app_name='post'
urlpatterns = [
    path('', views.nomajorlist),
    path('search/', views.PostSearchView.as_view(), name='post_searched'),
    path('search/sort/<str:query>/', views.post_search_sort, name='post_search_sort'),
    path('create_post/', views.PostCreate.as_view(), name='create_post'),
    path('delete_post/<int:pk>', views.PostDelete.as_view(), name='delete_post'),
    path('update_post/<int:pk>', views.PostUpdate.as_view(), name='update_post'),
    path('update_comment/<int:pk>', views.CommentUpdate.as_view(), name='update_comment'),
    path('delete_comment/<int:pk>', views.delete_comment, name='delete_comment'),
    path('<str:slug>/', views.major_page, name='Qlist'),
    path('<str:slug>/post_sort/', views.post_sort, name='post_sort'),
    path('<str:slug>/<int:pk>/', views.PostDetail.as_view(), name='post_detail'),
    path('<str:slug>/<int:pk>/upvote_post/', views.UpvotePostView.as_view(), name='upvote_post'),
    path('<str:slug>/<int:pk>/downvote_post/', views.DownvotePostView.as_view(), name='downvote_post'),
    path('<str:slug>/<int:pk>/new_comment/', views.new_comment),
    path('<str:slug>/<int:pk>/upvote_comment/<int:comment_pk>', views.UpvoteCommentView.as_view(), name='upvote_comment'),
    path('<str:slug>/<int:pk>/downvote_comment//<int:comment_pk>', views.DownvoteCommentView.as_view(), name='downvote_comment'),
]

single_pages/urls.py
from django.urls import path
from . import views

app_name = 'single_pages'
urlpatterns = [
    path('MyPage/', views.user, name='MyPage'),
    path('', views.main, name='main'),
    path('login/', views.login_view, name='login'),
    path('signup/', views.signup, name='signup'),
    path('single_pages:main', views.logout, name='logout'),
]

single_pages/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


# 유저에 전공부분 추가를 위해 설정
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    major = models.TextField(max_length=15)
    profile_picture = models.ImageField(upload_to='profile_pics/', null=True, blank=True)
    is_who = models.BooleanField(default=False)

single_pages/forms.py
from django import forms
from .models import Profile
from django.contrib.auth.models import User


class SignUpForm(forms.Form):
    username = forms.CharField(
        max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Duksung'}))
    email = forms.EmailField(
        max_length=254, widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'duksung@duksung.ac.kr'}))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))
    major = forms.CharField(
        max_length=50,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'major'})
    )

# 위에 코드만 사용했더니 비밀번호가 한자리여도 통과되는 문제가 생김... 유효성 검사하는 함수 추가

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")

        if len(password) < 8:
            self.add_error('password', '비밀번호는 8자 이상이어야 합니다.')

        elif password is None:   # TypeError: object of type 'NoneType' has no len() 오류 때문에 추가
            self.add_error('password', '비밀번호를 입력하세요.')

single_pages/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.shortcuts import render, redirect, get_object_or_404
from .forms import SignUpForm
from django.contrib import auth
from django.contrib.auth import get_user_model
from post.models import Post
from .models import Profile

# 사용자가 있는지 검사하는 함수


# Create your views here.
def main(request):
    return render(
        request,
        'single_pages/index.html'
    )


@login_required
def user(request):
    author = request.user
    post_list = Post.objects.filter(author=author).order_by('-pk')

    return render(
        request,
        'single_pages/MyPage.html',
        {
            'post_list': post_list,
        }
    )


def login(request):
    return render(
        request,
        'single_pages/login.html'
    )


def signup(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)

        if form.is_valid():  # 폼 내용 유효성검사 후 괜찮으면
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            major = form.cleaned_data['major']

            exist_user = User.objects.filter(username=username)
            if exist_user:
                # 사용자가 존재하기 때문에 사용자를 저장하지 않고 회원가입 페이지를 다시 띄움
                messages.warning(request, "이미 있는 이름입니다")
                return render(request, 'single_pages/signup.html')  # 오류메세지 뜨게 할 뭔가 없나

            new_user = User.objects.create_user(username=username, email=email, password=password)
            Profile.objects.create(user=new_user, major=major)
            # 새로운 사용자 User에 추가
            try:
                userp = User.objects.get(username='유제혁')
            except User.DoesNotExist:
                userp = None

            # 사용자 프로필 가져오기
            try:
                user_profile = Profile.objects.get(user=userp)
                # is_who 속성
                user_profile.is_who = True
                user_profile.save()
            except Profile.DoesNotExist:
                user_profile = None

            return redirect('/')
            # 회원가입 완료 후에 메인페이지로 이동

    else:
        form = SignUpForm()
        # 뭔가 내용 안 맞으면 다시 form 작성하도록

    context = {'form': form}
    return render(request, 'single_pages/signup.html', context)


def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username', None)
        password = request.POST.get('password', None)

        me = authenticate(request, username=username, password=password)

        if me is not None:
            auth_login(request, me)  # 사용자 로그인
            return redirect('/')

        else:
            messages.error(request, '아이디 혹은 비밀번호가 올바르지 않습니다.')
            return redirect('/login/')

    else:
        return render(request, 'single_pages/login.html')


def logout(request):
    auth.logout(request)
    return redirect('/')

single_pages/templates/single_pages/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <title>Login 08</title>
        <meta charset="utf-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />
        <link
            href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap"
            rel="stylesheet"
        />
        <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        />
        <link
            rel="stylesheet"
            href="{% static 'single_pages/login/css/style.css' %}"
        />
    </head>
    <body>
        <section class="ftco-section">
            <div class="container">
                <div class="row justify-content-center">
                    {% comment %}
                    <div class="col-md-6 text-center mb-5">
                        <h2 class="heading-section">Login</h2>
                    </div>
                    {% endcomment %}
                </div>
                <div class="row justify-content-center">
                    <div class="col-md-6 col-lg-5">
                        <div
                            class="icon d-flex align-items-center justify-content-center"
                            style="background-color: f8f9fa"
                        >
                            <img
                                src="{% static 'single_pages/images/duksung_symbol.png' %}"
                                alt="Duksung Symbol"
                                style="width: 100px; height: auto"
                            />
                        </div>
                        <h3
                            class="text-center mb-4"
                            style="color: rgb(183, 0, 80); font-weight: 700"
                        >
                            Have an account?
                        </h3>


                        <form action="{% url 'single_pages:login' %}" method="POST" class="login-form">
                            {% csrf_token %}
                            {% for m in messages %}
                                {{ m }}
                            {% endfor %}
                            <div class="form-group">
                                <input
                                    type="text"
                                    class="form-control rounded-left"
                                    placeholder="Username"
                                    id="username"
                                    name="username"
                                    required
                                />
                            </div>
                            <div class="form-group d-flex">
                                <input
                                    type="password"
                                    class="form-control rounded-left"
                                    placeholder="Password"
                                    id="password"
                                    name="password"
                                    required
                                />
                            </div>
                            <div class="form-group d-md-flex">
                                <div class="w-50 text-left">
                                    <label
                                        class="checkbox-wrap checkbox-primary"
                                    >
                                        Remember Me
                                        <input type="checkbox" checked />
                                        <span class="checkmark"></span>
                                    </label>
                                </div>
                                <div class="w-50 text-md-right">
                                    <a href="/signup/">Sign up</a>
                                </div>
                                <div class="w-50 text-md-right">
                                    <a href="#">Forgot Password</a>
                                </div>
                            </div>
                            <div class="form-group">
                                <button
                                    type="submit"
                                    class="btn btn-primary rounded submit p-3 px-5"
                                >
                                    Get Started
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>

        <script src="{% static 'single_pages/login/js/jquery.min.js' %}"></script>
        <script src="{% static 'single_pages/login/js/popper.js' %}"></script>
        <script src="{% static 'single_pages/login/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'single_pages/login/js/main.js' %}"></script>
    </body>
</html>

single_pages/templates/single_pages/signup.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <title>Sign Up 01</title>
        <meta charset="utf-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />

        <link
            href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap"
            rel="stylesheet"
        />
        <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        />
        <link
            rel="stylesheet"
            href="{% static 'single_pages/signup/css/style.css' %}"
        />
    </head>
    <style>
        body {
            font-family: "Lato", sans-serif;
        }

        .login-wrap img {
            width: 100px;
            height: auto;
            margin-bottom: 20px;
            display: block; /* 이미지를 블록 요소로 설정하여 가운데 정렬 가능하도록 함 */
            margin-left: auto;
            margin-right: auto;
        }

        .signup-form {
            max-width: 400px;
            margin: 0 auto;
        }

        .form-group {
            margin-bottom: 20px;
        }

        .toggle-password {
            cursor: pointer;
        }
    </style>

    <body>
        <section class="ftco-section">
            <div class="container">
                {% comment %}
                <div class="row justify-content-center">
                    <div class="col-md-6 text-center mb-5">
                        <h2 class="heading-section"></h2>
                    </div>
                </div>
                {% endcomment %}
                <div class="row justify-content-center">
                    <div class="col-md-7 col-lg-6 col-xl-5">
                        <div class="login-wrap p-4 p-md-5">
                            <div class="login-center" >
                                <img src="{% static 'single_pages/images/duksung_symbol.png' %}"
                                     alt="Duksung Symbol"
                                     style="width: 100px; height: auto"
                                />

                            </div>
                            <h3
                                class="text-center mb-4"
                                style="color: rgb(183, 0, 80); font-weight: 700"
                            >
                                Create Your Account
                            </h3>
                            <form action="{% url 'single_pages:signup' %}" method="POST" class="signup-form">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label class="label"
                                        >Full Name</label
                                    >
                                    <input
                                        type="text"
                                        class="form-control"
                                        name="username"
                                        placeholder="Duksung"
                                        id="username"
                                        value="{{ form.username.value|default_if_none:'' }}"
                                        required
                                    />
                                    {% for message in messages %}
                                        {{ message }}
                                    {% endfor %}
                                </div>
                                <div class="form-group">
                                    <label class="label" for="email"
                                        >Email Address</label
                                    >
                                    <input
                                        type="text"
                                        class="form-control"
                                        name="email"
                                        placeholder="duksung@duksung.ac.kr"
                                        id="email"
                                        value="{{ form.email.value|default_if_none:'' }}"
                                        required
                                    />

                                </div>
                                <div class="form-group">
                                    <label class="label"
                                        >Password</label
                                    >
                                    <input
                                        id="password-field"
                                        type="password"
                                        class="form-control"
                                        name="password"
                                        placeholder="Password"
                                        value="{{ form.password.value|default_if_none:'' }}"
                                        required
                                    />
                                    <span
                                        toggle="#password-field"
                                        class="fa fa-fw fa-eye field-icon toggle-password"
                                    ></span>
                                    {% for error in form.password.errors %}
                                        <span class="error-message">{{ error }}</span>
                                    {% endfor %}
                                </div>
                                <div class="form-group">
                                    <label class="label" for="major"
                                        >전공선택</label
                                    >
                                    <select name="major" id="major" required>
                                        <option value="IT미디어공학전공">IT미디어공학전공</option>
                                        <option value="경영학전공">경영학전공</option>
                                        <option value="수학전공">수학전공</option>
                                        <option value="실내디자인전공">실내디자인전공</option>
                                        <option value="컴퓨터공학전공">컴퓨터공학전공</option>

                                    </select>
<!--                                    <input-->
<!--                                        type="text"-->
<!--                                        class="form-control"-->
<!--                                        name="major"-->
<!--                                        placeholder="컴퓨터공학전공"-->
<!--                                        required-->
<!--                                    />-->


                                </div>
                                <div class="form-group d-md-flex">
                                    <div class="w-100 text-left">
                                        <label
                                            class="checkbox-wrap checkbox-primary"
                                            >I agree all statements in terms of
                                            service
                                            <input type="checkbox" checked />
                                            <span class="checkmark"></span>
                                        </label>
                                    </div>
                                </div>
                                <button
                                    type="submit"
                                    class="form-control btn btn-primary rounded submit px-3"
                                >
                                    Sign Up
                                </button>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <script src="{% static 'single_pages/signup/js/jquery.min.js' %}"></script>
        <script src="{% static 'single_pages/signup/js/popper.js' %}"></script>
        <script src="{% static 'single_pages/signup/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'single_pages/signup/js/main.js' %}"></script>
    </body>
</html>